### ISSUE TITLE
Build Fail on Android

### ISSUE THREAD

**Issue by johndev247** [smileidentity/react-native#65]
Now build on android is failing after IOS Build fixed in version 10.1.11
error: Task :smile_identity_react-native:compileDebugKotlin FAILED

React native v 0.74.3
@smile_identity/react-native v 10.1.11

**Comment by BalogunofAfrica** [comment]
You have to upgrade your Kotlin version to at least `1.9.23`

**Comment by ayinlaabel** [comment]
I am have the same issue

**Comment by logboi1** [comment]
am also facing the same issue, failed build on android, am using the latest version 10.2.1, am my kotlin version is 1.9.23

**Comment by nikul-nyusoft** [comment]
I'm still facing this issue, @logboi1 , @ayinlaabel , @BalogunofAfrica , @Yeboahmedia ,
Have you guys found any workaround or solution ?
Please share the correct kotlin versions if you have fixed the issue. 
Thanks in advance.

**Comment by jumaallan** [comment]
> I'm still facing this issue, [@logboi1](https://github.com/logboi1) , [@ayinlaabel](https://github.com/ayinlaabel) , [@BalogunofAfrica](https://github.com/BalogunofAfrica) , [@Yeboahmedia](https://github.com/Yeboahmedia) , Have you guys found any workaround or solution ? Please share the correct kotlin versions if you have fixed the issue. Thanks in advance.

can you share the error you are experiencing? it should work on any kotlin version @nikul-nyusoft

**Comment by nikul-nyusoft** [comment]
> > I'm still facing this issue, [@logboi1](https://github.com/logboi1) , [@ayinlaabel](https://github.com/ayinlaabel) , [@BalogunofAfrica](https://github.com/BalogunofAfrica) , [@Yeboahmedia](https://github.com/Yeboahmedia) , Have you guys found any workaround or solution ? Please share the correct kotlin versions if you have fixed the issue. Thanks in advance.
> 
> can you share the error you are experiencing? it should work on any kotlin version [@nikul-nyusoft](https://github.com/nikul-nyusoft)

Getting error like this:
org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
	at org.jetbrains.kotlin.protobuf.InvalidProtocolBufferException.invalidTag(InvalidProtocolBufferException.java:89)
	at org.jetbrains.kotlin.protobuf.CodedInputStream.readTag(CodedInputStream.java:158)
	at org.jetbrains.kotlin.metadata.jvm.JvmModuleProtoBuf$Module.<init>(JvmModuleProtoBuf.java:223)
	at org.jetbrains.kotlin.metadata.jvm.JvmModuleProtoBuf$Module.<init>(JvmModuleProtoBuf.java:188)
	at org.jetbrains.kotlin.metadata.jvm.JvmModuleProtoBuf$Module$1.parsePartialFrom(JvmModuleProtoBuf.java:341)
	at org.jetbrains.kotlin.metadata.jvm.JvmModuleProtoBuf$Module$1.parsePartialFrom(JvmModuleProtoBuf.java:336)
	at org.jetbrains.kotlin.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:192)
	at org.jetbrains.kotlin.protobuf.AbstractParser.parseFrom(AbstractParser.java:209)
	at org.jetbrains.kotlin.protobuf.AbstractParser.parseFrom(AbstractParser.java:49)
	at org.jetbrains.kotlin.metadata.jvm.JvmModuleProtoBuf$Module.parseFrom(JvmModuleProtoBuf.java:821)
	at org.jetbrains.kotlin.metadata.jvm.deserialization.ModuleMapping$Companion.loadModuleMapping(ModuleMapping.kt:82)
	at org.jetbrains.kotlin.load.kotlin.ModuleMappingUtilKt.loadModuleMapping(ModuleMappingUtil.kt:18)
	at org.jetbrains.kotlin.cli.jvm.compiler.JvmPackagePartProviderKt.tryLoadModuleMapping(JvmPackagePartProvider.kt:72)
	at org.jetbrains.kotlin.cli.jvm.compiler.JvmPackagePartProvider.addRoots(JvmPackagePartProvider.kt:54)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinCoreEnvironment.createPackagePartProvider(KotlinCoreEnvironment.kt:307)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1$1.invoke(KotlinToJVMBytecodeCompiler.kt:262)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.createContainer(TopDownAnalyzerFacadeForJVM.kt:198)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.createContainer$default(TopDownAnalyzerFacadeForJVM.kt:150)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration(TopDownAnalyzerFacadeForJVM.kt:101)
	at org.jetbrains.kotlin.cli.jvm.compiler.TopDownAnalyzerFacadeForJVM.analyzeFilesWithJavaIntegration$default(TopDownAnalyzerFacadeForJVM.kt:99)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:257)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler$analyze$1.invoke(KotlinToJVMBytecodeCompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.messages.AnalyzerWithCompilerReport.analyzeAndReport(AnalyzerWithCompilerReport.kt:115)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.analyze(KotlinToJVMBytecodeCompiler.kt:248)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:88)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli$default(KotlinToJVMBytecodeCompiler.kt:47)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:167)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:53)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:101)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:485)
	at org.jetbrains.kotlin.incremental.IncrementalJvmCompilerRunner.runCompiler(IncrementalJvmCompilerRunner.kt:131)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.doCompile(IncrementalCompilerRunner.kt:424)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileImpl(IncrementalCompilerRunner.kt:360)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compileNonIncrementally(IncrementalCompilerRunner.kt:242)
	at org.jetbrains.kotlin.incremental.IncrementalCompilerRunner.compile(IncrementalCompilerRunner.kt:98)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.execIncrementalCompiler(CompileServiceImpl.kt:625)
	at org.jetbrains.kotlin.daemon.CompileServiceImplBase.access$execIncrementalCompiler(CompileServiceImpl.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1746)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)

**Comment by jumaallan** [comment]
Should be fixed now - forgot to update the issue here
